INSERT INTO cards (filename, name, rarity, is_active, created_at) VALUES
('m4a1_s.jpg', 'M4A1 S', 'bronze', 1, datetime('now')),
('kill_confirmed.jpg', 'Kill Confirmed', 'silver', 1, datetime('now')),
('glock_18_fade.jpg', 'Glock 18 Fade', 'gold', 1, datetime('now')),
('blaze.jpg', 'Blaze', 'silver', 1, datetime('now')),
('redline.jpg', 'Redline', 'bronze', 1, datetime('now')),
('printstream.jpg', 'Printstream', 'bronze', 1, datetime('now')),
('hyper_beast.jpg', 'Hyper Beast', 'bronze', 1, datetime('now')),
('neo_noir.jpg', 'Neo Noir', 'bronze', 1, datetime('now')),
('fire_serpent.jpg', 'Fire Serpent', 'silver', 1, datetime('now')),
('awp_asiimov.jpg', 'AWP Asiimov', 'bronze', 1, datetime('now')),
('crimson_kimono.jpg', 'Crimson Kimono', 'gold', 1, datetime('now')),
('awp_medusa.jpg', 'AWP Medusa', 'gold', 1, datetime('now')),
('vice.jpg', 'Vice', 'gold', 1, datetime('now')),
('awp_gungnir.jpg', 'AWP Gungnir', 'gold', 1, datetime('now')),
('wild_lotus.jpg', 'Wild Lotus', 'platinum', 1, datetime('now')),
('m4a4.jpg', 'M4A4', 'platinum', 1, datetime('now')),
('dragon_lore.jpg', 'Dragon Lore', 'diamond', 1, datetime('now')),
('ak_47.jpg', 'AK 47', 'bronze', 1, datetime('now')),
('case_hardened.jpg', 'Case Hardened', 'diamond', 1, datetime('now'));
