UPDATE cards SET name='M4A1 S' WHERE filename='m4a1_s.jpg';
UPDATE cards SET name='Kill Confirmed' WHERE filename='kill_confirmed.jpg';
UPDATE cards SET name='Glock 18 Fade' WHERE filename='glock_18_fade.jpg';
UPDATE cards SET name='Blaze' WHERE filename='blaze.jpg';
UPDATE cards SET name='Redline' WHERE filename='redline.jpg';
UPDATE cards SET name='Printstream' WHERE filename='printstream.jpg';
UPDATE cards SET name='Hyper Beast' WHERE filename='hyper_beast.jpg';
UPDATE cards SET name='Neo Noir' WHERE filename='neo_noir.jpg';
UPDATE cards SET name='Fire Serpent' WHERE filename='fire_serpent.jpg';
UPDATE cards SET name='AWP Asiimov' WHERE filename='awp_asiimov.jpg';
UPDATE cards SET name='Crimson Kimono' WHERE filename='crimson_kimono.jpg';
UPDATE cards SET name='AWP Medusa' WHERE filename='awp_medusa.jpg';
UPDATE cards SET name='Vice' WHERE filename='vice.jpg';
UPDATE cards SET name='AWP Gungnir' WHERE filename='awp_gungnir.jpg';
UPDATE cards SET name='Wild Lotus' WHERE filename='wild_lotus.jpg';
UPDATE cards SET name='M4A4' WHERE filename='m4a4.jpg';
UPDATE cards SET name='Dragon Lore' WHERE filename='dragon_lore.jpg';
UPDATE cards SET name='AK 47' WHERE filename='ak_47.jpg';
UPDATE cards SET name='Case Hardened' WHERE filename='case_hardened.jpg';
