# Новые карты: (ключ файла static/nft/<key>.jpg, отображаемое название, ранг)
NEW_CARDS = [
    ('Grant_Remington', 'Grant Remington', 'gold'),
    ('adidas_samba', 'Adidas Samba', 'gold'),
    ('alaska', 'Alaska', 'gold'),
    ('alienware', 'Alienware', 'gold'),
    ('amazon_river', 'Amazon River', 'platinum'),
    ('angkor_thom', 'Angkor Thom', 'gold'),
    ('antarctica', 'Antarctica', 'gold'),
    ('apple_macintosh', 'Apple Macintosh', 'gold'),
    ('atari_2600', 'Atari 2600', 'gold'),
    ('atlantis', 'Atlantis', 'gold'),
    ('audi_a6', 'Audi A6', 'gold'),
    ('audi_q7', 'Audi Q7', 'gold'),
    ('audi_r8', 'Audi R8', 'gold'),
    ('australia', 'Australia', 'gold'),
    ('azzam', 'Azzam', 'diamond'),
    ('baccarat_les', 'Baccarat Les', 'platinum'),
    ('baikal', 'Baikal', 'platinum'),
    ('bali', 'Bali', 'platinum'),
    ('barracuda_1970', 'Barracuda 1970', 'gold'),
    ('basil_cathed', 'Cathedral', 'gold'),
    ('beeper', 'Beeper', 'gold'),
    ('beetle_1967', 'Beetle 1967', 'gold'),
    ('benz_sls_amg', 'Benz SLS AMG', 'platinum'),
    ('benz_w126', 'Benz W126', 'gold'),
    ('big_ben', 'Big Ben', 'platinum'),
    ('blessed_church', 'Blessed Church', 'gold'),
    ('bmw_adventure', 'BMW Adventure', 'platinum'),
    ('bmw_e30', 'BMW E30', 'gold'),
    ('bmw_e31', 'BMW E31', 'gold'),
    ('bmw_e39', 'BMW E39', 'gold'),
    ('bombier', 'Bombardier', 'diamond'),
    ('british_museum', 'British Museum', 'gold'),
    ('bugatti', 'Bugatti', 'diamond'),
    ('burj_al_arab', 'Burj Al Arab', 'platinum'),
    ('burj_khalifa', 'Burj Khalifa', 'platinum'),
    ('camaro_1967', 'Camaro 1967', 'gold'),
    ('canary_islands', 'Canary Islands', 'gold'),
    ('cannes_palme', 'Cannes Palme', 'diamond'),
    ('caribbean_islands', 'Caribbean Islands', 'platinum'),
    ('cartier_panthere', 'Cartier Panthere', 'platinum'),
    ('castillo_maya', 'Castillo Maya', 'gold'),
    ('centurion_card', 'Centurion Card', 'diamond'),
    ('chaika', 'Chaika', 'gold'),
    ('challenger_1970', 'Challenger 1970', 'gold'),
    ('chambord_castle', 'Chambord Castle', 'gold'),
    ('chanel_5', 'Chanel 5', 'platinum'),
    ('chevelle_ss', 'Chevelle SS', 'gold'),
    ('chichen_itza', 'Chichen Itza', 'platinum'),
    ('china_wall', 'China Wall', 'platinum'),
    ('chinese_pyramids', 'China Pyramid', 'gold'),
    ('christ__redeemer', 'Christ Redeemer', 'platinum'),
    ('chrome_hearts', 'Chrome Hearts', 'gold'),
    ('clive_christian', 'Clive Christian', 'diamond'),
    ('cologne_cathedral', 'Cologne Cathedral', 'gold'),
    ('colosseum', 'Colosseum', 'platinum'),
    ('colt_walker', 'Colt Walker', 'platinum'),
    ('commodore_64', 'Commodore 64', 'gold'),
    ('congo_rainforest', 'Congo Rainforest', 'gold'),
    ('corvair_1965', 'Corvair 1965', 'gold'),
    ('coutts_world', 'Coutts World', 'diamond'),
    ('cuba', 'Cuba', 'gold'),
    ('cybertruck', 'Cybertruck', 'platinum'),
    ('davinci_trophy', 'Davinci Trophy', 'diamond'),
    ('delorean', 'Delorean', 'gold'),
    ('diamond_black', 'Diamond Black', 'diamond'),
    ('diamond_clear', 'Diamond Clear', 'diamond'),
    ('diamond_red', 'Diamond Red', 'diamond'),
    ('dodge_charger', 'Dodge Charger', 'gold'),
    ('dubai_royale', 'Dubai Royale', 'diamond'),
    ('dvd_pioneer', 'DVD Pioneer', 'gold'),
    ('eagle_cabernet', 'Eagle Cabernet', 'platinum'),
    ('easter_island', 'Easter Island', 'gold'),
    ('eclipse', 'Eclipse', 'diamond'),
    ('eiffel_tower', 'Eiffel Tower', 'platinum'),
    ('etna', 'Etna', 'gold'),
    ('everest', 'Everest', 'platinum'),
    ('fairlady_roadster', 'Fairlady Roadster', 'gold'),
    ('fiat_500', 'Fiat 500', 'gold'),
    ('fifa_trophy', 'FIFA Trophy', 'diamond'),
    ('ford_gt40', 'Ford GT40', 'platinum'),
    ('ford_mustang', 'Ford Mustang', 'gold'),
    ('fuji_mountain', 'Fuji Mountain', 'gold'),
    ('game_boy', 'Game Boy', 'gold'),
    ('gelandewagen', 'Gelandewagen', 'platinum'),
    ('giza', 'Giza', 'platinum'),
    ('gold_and_wood', 'Gold And Wood', 'gold'),
    ('gold_bar', 'Gold Bar', 'diamond'),
    ('gold_dinar', 'Gold Dinar', 'gold'),
    ('golden_delicious', 'Golden Delicious', 'gold'),
    ('goldmund_reference', 'Goldmund', 'platinum'),
    ('gout_de_midas', 'Gout De Midas', 'platinum'),
    ('grand_canyon', 'Grand Canyon', 'gold'),
    ('gucci_crocodile', 'Gucci Crocodile', 'platinum'),
    ('gucci_stuart', 'Gucci Stuart', 'gold'),
    ('gulfstream', 'Gulfstream', 'diamond'),
    ('hanging_gardens', 'Hanging Gardens', 'platinum'),
    ('harley_davidson', 'Harley Davidson', 'gold'),
    ('heritage_cognac', 'Heritage Cognac', 'platinum'),
    ('hermes_constance', 'Hermes Belt', 'platinum'),
    ('hermes_matte', 'Hermes Matte', 'platinum'),
    ('hermitage', 'Hermitage', 'platinum'),
    ('himeji_castle', 'Himeji Castle', 'gold'),
    ('history_supreme', 'History Supreme', 'diamond'),
    ('hollywood', 'Hollywood', 'gold'),
    ('holy_bible', 'Holy Bible', 'platinum'),
    ('honda_fireblade', 'Honda Fireblade', 'gold'),
    ('hope_diamond', 'Hope Diamond', 'diamond'),
    ('hot_fantasy', 'Hot Fantasy', 'platinum'),
    ('ibiza', 'Ibiza', 'gold'),
    ('ibm_pc', 'IBM PC', 'gold'),
    ('ibuy_power', 'iBuyPower', 'gold'),
    ('iphone_1', 'iPhone 1', 'platinum'),
    ('iphone_17', 'iPhone 17', 'gold'),
    ('iphone_6', 'iPhone 6', 'gold'),
    ('iphone_butterfly', 'iPhone Butterfly', 'gold'),
    ('iphone_xx', 'iPhone XX', 'gold'),
    ('j._p._morgan', 'J. P. Morgan', 'diamond'),
    ('jamaica', 'Jamaica', 'gold'),
    ('jerusalem', 'Jerusalem', 'gold'),
    ('jet_777x', 'Jet 777X', 'diamond'),
    ('jin_mao', 'Jin Mao', 'gold'),
    ('jvc__rc_m70', 'JVC RC M70', 'gold'),
    ('jvc_vhs', 'JVC Vhs', 'gold'),
    ('karmann_ghia', 'Karmann Ghia', 'gold'),
    ('kawasaki_ninja', 'Kawasaki Ninja', 'gold'),
    ('kazantip', 'Kazantip', 'gold'),
    ('kopeika', 'Kopeika', 'gold'),
    ('lamborghini', 'Lamborghini', 'platinum'),
    ('las_vegas', 'Las Vegas', 'gold'),
    ('lincoln_memorial', 'Lincoln Memorial', 'gold'),
    ('london', 'London', 'gold'),
    ('louis_vuitton_belt', 'Louis Vuitton Belt', 'gold'),
    ('louis_vuitton_zippy', 'LV Zippy', 'platinum'),
    ('louvre', 'Louvre', 'platinum'),
    ('macbook_pro_16', 'MacBook Pro 16', 'gold'),
    ('maldives', 'Maldives', 'platinum'),
    ('maserati', 'Maserati', 'platinum'),
    ('mauna_loa', 'Mauna Loa', 'gold'),
    ('mclaren', 'McLaren', 'diamond'),
    ('mining_farm', 'Mining Farm', 'gold'),
    ('mma_belt', 'MMA Belt', 'diamond'),
    ('mont_michel', 'Mont Michel', 'gold'),
    ('morreale_paris', 'Morreale Paris', 'gold'),
    ('moscow_kremlin', 'Moscow Kremlin', 'platinum'),
    ('moskvich', 'Moskvich', 'gold'),
    ('mother_statue', 'Mother Statue', 'gold'),
    ('mount_rushmore', 'Mount Rushmore', 'gold'),
    ('new_balance', 'New Balance', 'gold'),
    ('new_zeland', 'New Zealand', 'gold'),
    ('niagara_falls', 'Niagara Falls', 'platinum'),
    ('nike_jordan_1', 'Nike Jordan 1', 'gold'),
    ('nile_river', 'Nile River', 'platinum'),
    ('nintendo_switch', 'Nintendo Switch', 'gold'),
    ('nobel_medal', 'Nobel Medal', 'diamond'),
    ('nokia_3310', 'Nokia 3310', 'gold'),
    ('north_pole', 'North Pole', 'gold'),
    ('oakley_c_six', 'Oakley C Six', 'gold'),
    ('off_white_belt', 'Off White Belt', 'gold'),
    ('opera_oslo', 'Opera Oslo', 'gold'),
    ('osaka_castle', 'Osaka Castle', 'gold'),
    ('oscar_trophy', 'Oscar Trophy', 'diamond'),
    ('palaroid', 'Polaroid', 'gold'),
    ('peacock', 'Peacock', 'gold'),
    ('pepe_diamond', 'Pepe Diamond', 'diamond'),
    ('pepe_gold', 'Pepe Gold', 'gold'),
    ('pepe_platinum', 'Pepe Platinum', 'platinum'),
    ('peru', 'Peru', 'gold'),
    ('petra', 'Petra', 'platinum'),
    ('pink_star', 'Pink Star', 'diamond'),
    ('pontiac_gto', 'Pontiac GTO', 'gold'),
    ('porsche_356', 'Porsche 356', 'platinum'),
    ('prada_ostrich', 'Prada Ostrich', 'platinum'),
    ('ps_5_pro', 'PS 5 Pro', 'gold'),
    ('quran', 'Quran', 'platinum'),
    ('ray_ban_wayfarer', 'Ray Ban', 'gold'),
    ('renault_dauph', 'Renault Dauphine', 'gold'),
    ('rolls_royce', 'Rolls Royce', 'diamond'),
    ('royal_fantasy', 'Royal Fantasy', 'platinum'),
    ('sagrada_familia', 'Sagrada Familia', 'platinum'),
    ('sahara_desert', 'Sahara Desert', 'gold'),
    ('salvatore_ferragamo', 'Ferragamo', 'gold'),
    ('samara', 'Samara', 'gold'),
    ('sgh_e330', 'SGH E330', 'gold'),
    ('shelby_cobra', 'Shelby Cobra', 'platinum'),
    ('shiels_emerald', 'Shiels Emerald', 'diamond'),
    ('siberia', 'Siberia', 'gold'),
    ('sony_handycam', 'Sony Handycam', 'gold'),
    ('sony_walkman', 'Sony Walkman', 'gold'),
    ('splendor_fantasy', 'Splendor Fantasy', 'platinum'),
    ('star_fantasy', 'Star Fantasy', 'platinum'),
    ('statue_of_liberty', 'Statue Of Liberty', 'platinum'),
    ('stratocaster', 'Stratocaster', 'gold'),
    ('stratus_rewards', 'Stratus Rewards', 'diamond'),
    ('susan_rosen', 'Susan Rosen', 'gold'),
    ('sydney_opera', 'Sydney Opera', 'gold'),
    ('taj_mahal', 'Taj Mahal', 'platinum'),
    ('tamagotchi', 'Tamagotchi', 'gold'),
    ('telegram_company', 'Telegram Corp', 'gold'),
    ('tesla_model_3', 'Tesla Model 3', 'gold'),
    ('tesla_model_y', 'Tesla Model Y', 'gold'),
    ('texas_paterson', 'Texas Paterson', 'platinum'),
    ('thinkpad_x1', 'ThinkPad X1', 'gold'),
    ('thunderbird_1955', 'Thunderbird 1955', 'gold'),
    ('tiktok_company', 'TikTok Company', 'gold'),
    ('torah', 'Torah', 'platinum'),
    ('triumph_spitfire', 'Triumph Spitfire', 'gold'),
    ('uaz', 'UAZ', 'gold'),
    ('ural', 'Ural', 'gold'),
    ('valerio_adami', 'Valerio Adami', 'gold'),
    ('vengeance', 'Vengeance', 'gold'),
    ('venice', 'Venice', 'gold'),
    ('vodka_billionaire', 'Vodka Billionaire', 'platinum'),
    ('volga', 'Volga', 'gold'),
    ('wailing_wall', 'Wailing Wall', 'gold'),
    ('wartburg_castle', 'Wartburg Castle', 'gold'),
    ('washington_boutet', 'Washington', 'platinum'),
    ('woodstock', 'Woodstock', 'gold'),
    ('xbox_x', 'Xbox X', 'gold'),
    ('yava', 'Yava', 'gold'),
    ('youtube_company', 'YouTube Corp', 'gold'),
    ('zaporozhets', 'Zaporozhets', 'gold'),
    ('zenit', 'Zenit', 'gold'),
    ('zephyrus_g16', 'Zephyrus G16', 'gold'),
    ('zeus', 'Zeus', 'gold'),
]
